In [2]:
import numpy as np
def minimize_travel_time(n, goal):
    P = np.zeros((n + 1, n + 1))
    print(P)
    for i in range(1, n):
        print(i)
        P[i, i + 1] = 0.5  
        P[i, min(2*i, n)] = 0.5  

    V = np.zeros(n + 1)
    theta = 1e-5  
    discount = 1.0  

    while True:
        delta = 0
        for s in range(1, n):
            v = V[s]
            V[s] = np.max([1 + discount * np.dot(P[s, :], V)])
            delta = max(delta, abs(v - V[s]))
        if delta < theta:
            break
    return int(V[goal])

n = int(input("Enter no.of Blocks: "))
goal_block = int(input("Enter the Goal Block: "))

result = minimize_travel_time(n, goal_block)
print("Minimum travel time to reach block", goal_block, "is", result, "minutes.")

Enter no.of Blocks: 7
Enter the Goal Block: 4
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
1
2
3
4
5
6
Minimum travel time to reach block 4 is 1 minutes.
